#!/bin/bash

# 2.3.0, 2.4.0, 2.5.0, 2.5.12, 3.0.0, 3.0.1
central_release_addons_url='https://repo1.maven.org/maven2/org/openhab/distro/openhab-addons/${version}/openhab-addons-${version}.kar'
central_release_legacy_addons_url='https://repo1.maven.org/maven2/org/openhab/distro/openhab-addons-legacy/${version}/openhab-addons-legacy-${version}.kar'

# 3.1.0.M3, 3.1.0.M4, 3.1.0.M5, 3.1.0.RC1, 3.2.0.M1, 3.2.0.M2, 3.2.0.M3, 3.2.0.M4
jfrog_milestone_addons_url='https://openhab.jfrog.io/artifactory/libs-milestone-local/org/openhab/distro/openhab-addons/${version}/openhab-addons-${version}.kar'

# 2.5.12, 3.0.1, 3.0.2, 3.1.0
jfrog_release_addons_url='https://openhab.jfrog.io/artifactory/libs-release-local/org/openhab/distro/openhab-addons/${version}/openhab-addons-${version}.kar'

# 3.2.0-SNAPSHOT
jenkins_addons_url='https://ci.openhab.org/job/openHAB3-Distribution/lastSuccessfulBuild/artifact/distributions/openhab-addons/target/openhab-addons-${version}.kar'

add_file_kar() {
    local kar_file="$1"
    local basename=$(basename $kar_file)
    local version=$(sed -E 's#.+-([0-9].+)\.kar#\1#g' <<< $basename)

    if [ $(grep -E '^.+\.(M|RC).+$' <<< $version ) ]; then
        type="milestone"
    elif [ $(grep -E '^.+-SNAPSHOT$' <<< $version) ]; then
        type="snapshot"
    else
        type="release"
    fi

    # explode KAR file to repository
    unzip -o "$kar_file" -x "META-INF/*" -d "libs-$type"

    # generate SHA1 checksum files
    for file in $(unzip -Z1 "$kar_file" | grep -Ev '(^META-INF/|.+/$)'); do
        local repo_file="libs-$type/$file"
        local sha1_file="libs-$type/$file.sha1"
        echo " generating: $sha1_file"
        sha1sum "$repo_file" | awk '{ print $1 }' > "$sha1_file"
    done
}

add_downloaded_version_kars() {
    local version="$1"
    local urls=()

    case $version in
    2.*)
        urls+=($(eval "echo $central_release_addons_url"))
        urls+=($(eval "echo $central_release_legacy_addons_url"))
        ;;
    3.*-SNAPSHOT)
        urls+=($(eval "echo $jenkins_addons_url"))
        ;;
    3.*.M*|3.*.RC*)
        urls+=($(eval "echo $jfrog_milestone_addons_url"))
        ;;
    3.0.0|3.0.1)
        urls+=($(eval "echo $central_release_addons_url"))
        ;;
    3.*)
        urls+=($(eval "echo $jfrog_release_addons_url"))
        ;;
    esac

    if [ ${#urls[@]} -eq 0 ]; then
        echo "There are no download URLs for version '$version'" >&2
    else
        for url in "${urls[@]}"; do
            local kar_file="kars/$(basename $url)"
            if wget $url -O "$kar_file"; then
                add_file_kar "$kar_file"
            fi
        done
    fi
}


for arg in "$@"; do
    if [ -f "$arg" ]; then
        add_file_kar "$arg"
    else
        add_downloaded_version_kars $arg
    fi
done
